### ISSUE TITLE
As an admissions counselor, I want to change the status of an application so that I can record my admissions decisions

### ISSUE THREAD

**Issue by varunsubbiah** [JDD8137/CommonApp#15]
Scenario: The counselor selects a new status for the application
Given the admissions counselor is viewing an application
When they select a new status from the dropdown
Then the status will be updated
Scenario: The counselor selects the same status for the application
Given the admissions counselor is viewing an application
When they select the same status from the dropdown as was previously selected
Then nothing will happen

**Comment by copycatchiller** [comment]
Completed this in Sprint 4. Note that this lives in a separate repo within the same organization (github.com/JDD8137/CommonAppWeb) as it is part of the web app and not the mobile app.
